# Generated by Django 4.0 on 2021-12-15 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
